version: "3"

services:
  postgres:
    image: "postgres:11.5"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=Nest"
      - "POSTGRES_PASSWORD=ZXCV1324"
    expose:
      - "5434"
    ports:
      - "5434:5434"